# FIXME: Each dist only has packages for *one* PHP version for Apache.
#        Even if they pre-install several versions, these are only CLI.
#        Rebuild this matrix. Perhaps run tests in parallel to speed things up,
#         or try to run on different dists. I didn't see it documented, but we can try.
#        https://docs.travis-ci.com/user/speeding-up-the-build
# FIXME: Rebuild this matrix.
#        https://docs.travis-ci.com/user/customizing-the-build/#naming-jobs-within-matrices
#        https://docs.travis-ci.com/user/build-matrix/
language: php
php:
  # Xenial only comes with 7.0. Sure, Travis installed other PHP versions, but
  #  only their CLI versions. Nice for testing PHPUnit but not for testing LOVD.
  # We could maybe use php-fpm to fix that, but we require a lot of other packages:
  # https://docs.travis-ci.com/user/languages/php/#apache--php
  - 7.0

env:
  # Let Selenium use Firefox driver.
  - LOVD_SELENIUM_DRIVER=firefox
  # Let Selenium use Chrome driver.
  - LOVD_SELENIUM_DRIVER=chrome

os: linux
# xenial = 16.04 LTS. PHP 7.0. Next is bionic (18.04), with PHP 7.2.
# xenial comes with Firefox 63.0.1 (use addons: firefox: "76.0" or so to upgrade), and MySQL 5.7.
# xenial is the current default (2020-05-11) and probably will be for a while (2021?), Travis normally lags behind 3 years.
dist: xenial

git:
  depth: 1

addons:
  chrome: stable
  apt:
    packages:
    - mutt # For mailing screenshots if uploading fails.
    - apache2
    - libapache2-mod-php
    - php-curl
    - php-gd
    - php-json
    - php-mbstring
    - php-mysql
    - php-zip # For uploading files.
    - exim4
    - jq # For using file.io.

services:
  - mysql
  - xvfb

before_install:
  - ./tests/travis/setup/setup_mysql.sh
  - ./tests/travis/setup/setup_apache.sh --githubaccount=LOVDnl
  - ./tests/travis/setup/setup_php.sh
  - ./tests/travis/setup/setup_config.sh
  - ./tests/travis/setup/setup_selenium_server.sh

before_script:
  - firefox --version
  - google-chrome --version

script:
  # Use vendor/bin/phpunit to start tests.

  # This is a travis test. This tests if travis is working as expected.
  # Two test are done which are independent of LOVD.
  - vendor/bin/phpunit --configuration ./tests/selenium_tests/phpunit.xml ./tests/travis/tests/

  # Run all test suites, starting at the unit tests.
  - vendor/bin/phpunit -v --configuration ./tests/unit_tests/phpunit.xml
  - vendor/bin/phpunit -v --configuration ./tests/selenium_tests/phpunit.xml --testsuite admin_tests
  - vendor/bin/phpunit -v --testsuite authorization_tests --configuration ./tests/selenium_tests/phpunit.xml
  - vendor/bin/phpunit -v --testsuite collaborator_tests --configuration ./tests/selenium_tests/phpunit.xml
  - vendor/bin/phpunit -v --testsuite curator_tests --configuration ./tests/selenium_tests/phpunit.xml
  - vendor/bin/phpunit -v --testsuite import_tests --configuration ./tests/selenium_tests/phpunit.xml
  - vendor/bin/phpunit -v --testsuite manager_tests --configuration ./tests/selenium_tests/phpunit.xml
  - vendor/bin/phpunit -v --testsuite submitter_tests --configuration ./tests/selenium_tests/phpunit.xml
  - vendor/bin/phpunit -v --testsuite access_sharing_tests --configuration ./tests/selenium_tests/phpunit.xml
  - vendor/bin/phpunit -v --testsuite find_replace_tests --configuration ./tests/selenium_tests/phpunit.xml

notifications:
  email:
   recipients:
      - I.F.A.C.Fokkema@lumc.nl
   on_success: never
   ## [always|never|change] # default: change
   on_failure: always
   ## [always|never|change] # default: always
