language: php
php:
  # Xenial only comes with 7.0. Sure, Travis installed other PHP versions, but
  #  only their CLI versions. Nice for testing PHPUnit but not for testing LOVD.
  # We could maybe use php-fpm to fix that, but we require a lot of other packages:
  # https://docs.travis-ci.com/user/languages/php/#apache--php
  - 7.0

env:
  # Let Selenium use Firefox driver.
  # - LOVD_SELENIUM_DRIVER=firefox # 2020-07-21: Disabled, Travis' FF has been failing for weeks, reason unknown.
  # Let Selenium use Chrome driver.
  - LOVD_SELENIUM_DRIVER=chrome

os: linux
# xenial = 16.04 LTS. PHP 7.0. Next is bionic (18.04), with PHP 7.2.
# xenial comes with Firefox 63.0.1 (use addons: firefox: "76.0" or so to upgrade), and MySQL 5.7.
# xenial is the current default (2020-05-11) and probably will be for a while (2021?), Travis normally lags behind 3 years.
dist: xenial

git:
  depth: 1

addons:
  chrome: stable
  apt:
    packages:
    - mutt # For mailing screenshots if uploading fails.
    - apache2
    - libapache2-mod-php
    - php-curl
    - php-gd
    - php-json
    - php-mbstring
    - php-mysql
    - php-zip # For uploading files.
    - exim4
    - jq # For using file.io.

services:
  - mysql
  - xvfb

before_install:
  - ./tests/travis/setup/setup_mysql.sh
  - ./tests/travis/setup/setup_apache.sh --githubaccount=LOVDnl
  - ./tests/travis/setup/setup_php.sh
  - ./tests/travis/setup/setup_config.sh
  - ./tests/travis/setup/setup_selenium_server.sh

before_script:
  - firefox --version
  - google-chrome --version

script:
  # Use vendor/bin/phpunit to start tests.
  # Run all test suites, starting at the unit tests.
  - vendor/bin/phpunit -v --configuration ./tests/unit_tests/phpunit.xml
  - vendor/bin/phpunit -v --configuration ./tests/selenium_tests/phpunit.xml --testsuite admin_tests
  - vendor/bin/phpunit -v --configuration ./tests/selenium_tests/phpunit.xml --testsuite manager_tests
  - vendor/bin/phpunit -v --configuration ./tests/selenium_tests/phpunit.xml --testsuite curator_tests
  - vendor/bin/phpunit -v --configuration ./tests/selenium_tests/phpunit.xml --testsuite collaborator_tests
  - vendor/bin/phpunit -v --configuration ./tests/selenium_tests/phpunit.xml --testsuite submitter_tests

notifications:
  email:
   recipients:
      - I.F.A.C.Fokkema@lumc.nl
   on_success: never
   ## [always|never|change] # default: change
   on_failure: always
   ## [always|never|change] # default: always
