language: php
php:
  # aliased to a recent 5.4.x version
  - 5.4
  # aliased to a recent 5.5.x version
  - 5.5
  # aliased to a recent 5.6.xversion  
  - 5.6
  # aliased to a recent 7.x version
  - 7.0
  
addons:
  firefox: "40.0"

sudo: required

before_install:
  - ./tests/travis/setup/setup_mysql.sh

before_script:
  - ./tests/travis/setup/setup_apache.sh --githubaccount=LOVDnl
  - ./tests/travis/setup/setup_config.sh
  - ./tests/travis/setup/setup_selenium_server.sh

script:
  # Use phpunit or vendor/bin/phpunit to start tests.  
  # vendor/bin/phpunit is the best option to run the tests. Because this one 
  # is installed via composer. 
  # Not running phpunit installed via composer gives errors, has to do with the 
  # versions of the dependencies. 
  
  # This is a travis test. This test if travis is working as expected. 
  # Two test are done which are independent of LOVD.
  - vendor/bin/phpunit ./tests/travis/tests/

  # Run all test suites.
  - vendor/bin/phpunit -v --testsuite admin_tests --configuration ./tests/selenium_tests/phpunit.xml
  - vendor/bin/phpunit -v --testsuite authorization_tests --configuration ./tests/selenium_tests/phpunit.xml
  - vendor/bin/phpunit -v --testsuite collaboration_tests --configuration ./tests/selenium_tests/phpunit.xml
  - vendor/bin/phpunit -v --testsuite curator_tests --configuration ./tests/selenium_tests/phpunit.xml
  - vendor/bin/phpunit -v --testsuite import_tests --configuration ./tests/selenium_tests/phpunit.xml
  - vendor/bin/phpunit -v --testsuite manager_tests --configuration ./tests/selenium_tests/phpunit.xml
  - vendor/bin/phpunit -v --testsuite submitter_tests --configuration ./tests/selenium_tests/phpunit.xml
  - vendor/bin/phpunit -v --testsuite temp_tests --configuration ./tests/selenium_tests/phpunit.xml

after_failure:
  - ./tests/upload_test_results.sh

notifications: 
  email:
   recipients:
      - I.F.A.C.Fokkema@lumc.nl
      - M.Kroon@lumc.nl
   on_success: never
   ## [always|never|change] # default: change
   on_failure: always 
   ## [always|never|change] # default: always