language: php
php:
  # aliased to a recent 5.6.x version
  #- 5.6
  # aliased to a recent 7.1.x version
  #- 7.1
  # aliased to a recent 7.2.x version
  - 7.2

env:
  # Let Selenium use Firefox driver.
  - LOVD_SELENIUM_DRIVER=firefox
  # Let Selenium use Chrome driver.
  - LOVD_SELENIUM_DRIVER=chrome

#matrix:
#  exclude:
#    # Exclude some combinations of php version and selenium driver.
#    - php: 5.6
#      env: LOVD_SELENIUM_DRIVER=chrome
#    - php: 7.1
#      env: LOVD_SELENIUM_DRIVER=firefox

sudo: required
dist: xenial

addons:
#  firefox: "54.0"
  apt:
#    sources:
#      - google-chrome
    packages:
    - mysql-server
    - mysql-client
    - mutt
#    - chromium-browser=61.0.3163.100-0ubuntu0.14.04.1202
    - chromium-browser
    - apache2
    - libapache2-mod-php
    - php-curl
    - php-gd
    - php-json
    - php-mbstring
    - php-mysql

services:
  - mysql
  - xvfb

before_install:
  - ./tests/travis/setup/setup_chrome.sh
  - ./tests/travis/setup/setup_mysql.sh
  - ./tests/travis/setup/setup_apache.sh --githubaccount=LOVDnl
  - ./tests/travis/setup/setup_php.sh
  - ./tests/travis/setup/setup_config.sh
  - ./tests/travis/setup/setup_selenium_server.sh

script:
  # Use phpunit or vendor/bin/phpunit to start tests.
  # vendor/bin/phpunit is the best option to run the tests. Because this one
  # is installed via composer.
  # Not running phpunit installed via composer gives errors, has to do with the
  # versions of the dependencies.

  # This is a travis test. This test if travis is working as expected.
  # Two test are done which are independent of LOVD.
  - vendor/bin/phpunit --configuration ./tests/selenium_tests/phpunit.xml ./tests/travis/tests/

  # Run all test suites.
  - vendor/bin/phpunit -v --testsuite admin_tests --configuration ./tests/selenium_tests/phpunit.xml
  - ./tests/upload_test_results.sh
#  - vendor/bin/phpunit -v --testsuite authorization_tests --configuration ./tests/selenium_tests/phpunit.xml
#  - ./tests/upload_test_results.sh
#  - vendor/bin/phpunit -v --testsuite collaborator_tests --configuration ./tests/selenium_tests/phpunit.xml
#  - ./tests/upload_test_results.sh
#  - vendor/bin/phpunit -v --testsuite curator_tests --configuration ./tests/selenium_tests/phpunit.xml
#  - ./tests/upload_test_results.sh
#  - vendor/bin/phpunit -v --testsuite import_tests --configuration ./tests/selenium_tests/phpunit.xml
#  - ./tests/upload_test_results.sh
#  - vendor/bin/phpunit -v --testsuite manager_tests --configuration ./tests/selenium_tests/phpunit.xml
#  - ./tests/upload_test_results.sh
#  - vendor/bin/phpunit -v --testsuite submitter_tests --configuration ./tests/selenium_tests/phpunit.xml
#  - ./tests/upload_test_results.sh
#  - vendor/bin/phpunit -v --testsuite access_sharing_tests --configuration ./tests/selenium_tests/phpunit.xml
#  - ./tests/upload_test_results.sh
#  - vendor/bin/phpunit -v --testsuite find_replace_tests --configuration ./tests/selenium_tests/phpunit.xml
#  - ./tests/upload_test_results.sh
#  - vendor/bin/phpunit -v --configuration ./tests/unit_tests/phpunit.xml
#  - ./tests/upload_test_results.sh

notifications:
  email:
   recipients:
      - I.F.A.C.Fokkema@lumc.nl
   on_success: never
   ## [always|never|change] # default: change
   on_failure: always
   ## [always|never|change] # default: always
